In [4]:
import numpy as np
import pandas as pd
from pandas_datareader import data as web
import scipy.optimize as sco
import scipy.interpolate as sci

In [7]:
# Create a list of symbols
symbols = [
  "XOM", "SHW", "JPM", "AEP", "UNH", "AMZN", 
  "KO", "BA", "AMT", "DD", "TSN", "SLG"
]
# Initialize data container
asset_data = pd.DataFrame()
# For loop to get data from Yahoo finance
for sym in symbols:
  # Each run of the loop returns a pandas data frame
  asset_data[sym] = web.DataReader(name = sym, data_source = 'yahoo',start = '2021-09-13')['Adj Close']
# Set column indices
asset_data.columns = symbols
# Examine the first 5 rows
asset_data.head(n = 5)

,XOM,SHW,JPM,AEP,UNH,AMZN,KO,BA,AMT,DD,TSN,SLG
Date,,,,,,,,,,,,
2021-09-13,54.635735,301.571320,158.902466,87.498909,413.172394,3457.169922,55.221767,214.479996,291.792999,70.394516,76.000618,64.669189
2021-09-14,53.856216,298.366608,156.129196,87.013466,411.198853,3450.000000,55.261456,211.570007,293.565918,68.203094,75.006233,64.792725
2021-09-15,55.671810,298.915710,157.212662,86.518112,416.162659,3475.790039,55.449997,214.220001,294.417694,69.737091,75.781853,65.220291
2021-09-16,55.079769,297.527985,157.143066,85.180664,415.484863,3488.239990,54.924072,213.360001,294.298828,70.364632,75.374161,65.324821
2021-09-17,54.428520,293.255066,156.735519,83.318138,418.794067,3462.520020,54.021076,213.360001,290.941254,68.641380,75.384102,64.954247

In [10]:
def log_ro_daily(df):
    """
    Calculates the daily rate of return of a portfolio
    """
    d0 = df.pct_change().dropna(axis=0, how='any')
    d0 = np.log(df) - np.log(df.shift(1))

    return d0

In [8]:
log_ro_daily(asset_data)

,XOM,SHW,JPM,AEP,UNH,AMZN,KO,BA,AMT,DD,TSN,SLG
Date,,,,,,,,,,,,
2021-09-14,-0.014268,-0.010627,-0.017453,-0.005548,-0.004777,-0.002074,0.000719,-0.013568,0.006076,-0.031131,-0.013084,0.001910
2021-09-15,0.033712,0.001840,0.006940,-0.005693,0.012072,0.007475,0.003412,0.012525,0.002901,0.022492,0.010341,0.006599
2021-09-16,-0.010634,-0.004643,-0.000443,-0.015459,-0.001629,0.003582,-0.009485,-0.004015,-0.000404,0.008999,-0.005380,0.001603
2021-09-17,-0.011824,-0.014361,-0.002593,-0.021866,0.007965,-0.007373,-0.016441,0.000000,-0.011409,-0.024490,0.000132,-0.005673
2021-09-20,-0.026650,-0.006707,-0.029934,-0.009512,-0.017755,-0.030842,-0.006980,-0.018091,-0.008715,-0.014221,-0.001451,-0.005120
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-21,0.022650,-0.003575,0.013966,-0.005503,0.007194,0.019979,0.003997,0.058574,-0.002191,0.017019,0.005068,0.023175
2021-12-22,0.008099,0.012646,0.003908,-0.001499,0.014203,0.003638,0.007097,0.010876,0.012237,0.006668,-0.003987,0.002954
2021-12-23,0.000492,-0.001004,0.003574,-0.001155,0.002530,0.000184,0.000688,0.012544,-0.004002,0.020000,0.003415,0.006873
2021-12-27,0.014258,0.021189,0.005723,0.006473,0.008317,-0.008178,0.007386,-0.005142,0.025185,0.016170,0.011030,0.008916
2021-12-28,-0.003232,0.008248,0.003035,0.012977,0.006887,0.005844,0.003922,0.014569,0.009553,0.008019,0.005919,-0.002209

In [11]:
datalog_ro_daily(asset_data)

,XOM,SHW,JPM,AEP,UNH,AMZN,KO,BA,AMT,DD,TSN,SLG
Date,,,,,,,,,,,,
2021-09-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-14,-0.014370,-0.010684,-0.017607,-0.005563,-0.004788,-0.002076,0.000718,-0.013661,0.006058,-0.031625,-0.013170,0.001908
2021-09-15,0.033156,0.001839,0.006916,-0.005709,0.011999,0.007448,0.003406,0.012448,0.002897,0.022242,0.010288,0.006577
2021-09-16,-0.010691,-0.004653,-0.000443,-0.015579,-0.001630,0.003576,-0.009530,-0.004023,-0.000404,0.008958,-0.005394,0.001601
2021-09-17,-0.011894,-0.014466,-0.002597,-0.022108,0.007933,-0.007401,-0.016577,0.000000,-0.011474,-0.024795,0.000132,-0.005689
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-21,0.022398,-0.003581,0.013870,-0.005518,0.007168,0.019782,0.003989,0.056923,-0.002193,0.016876,0.005056,0.022911
2021-12-22,0.008067,0.012567,0.003900,-0.001500,0.014103,0.003632,0.007072,0.010817,0.012162,0.006645,-0.003995,0.002950
2021-12-23,0.000492,-0.001004,0.003567,-0.001155,0.002527,0.000184,0.000687,0.012466,-0.004010,0.019803,0.003409,0.006850
2021-12-27,0.014157,0.020968,0.005707,0.006452,0.008282,-0.008212,0.007359,-0.005155,0.024873,0.016041,0.010970,0.008877
2021-12-28,-0.003237,0.008214,0.003030,0.012893,0.006863,0.005827,0.003914,0.014464,0.009508,0.007987,0.005902,-0.002212